# Generated by Django 5.1.1 on 2024-09-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.TextField(max_length=1000)),
                ('topic_name', models.TextField(max_length=1000)),
                ('status', models.CharField(default='To do', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
