# Generated by Django 5.1.1 on 2024-09-15 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthomeworkapp', '0001_initial'),
        ('studentregisterapp', '0003_alter_studentregistrationmodel_confirm_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomeworkmodel',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='studentregisterapp.studentregistrationmodel'),
        ),
        migrations.AlterField(
            model_name='studenthomeworkmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenthomeworkmodel',
            name='status',
            field=models.CharField(default='To do', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studenthomeworkmodel',
            name='subject_name',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='studenthomeworkmodel',
            name='topic_name',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
