# Generated by Django 5.1.1 on 2024-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregisterapp', '0002_studentregistrationmodel_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='confirm_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
