# Generated by Django 5.1.1 on 2024-09-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentregisterapp', '0003_alter_studentregistrationmodel_confirm_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistrationmodel',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentregistrationmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentregistrationmodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
